In [2]:
import torch
import matplotlib.pyplot as plt
import numpy as np

## Generate 2D tensor

In [12]:
#torch.arange(start, end, step) returns size of (end-start)/step tensor
#torch.range(start, end, step) returns size of (end-start)/step + 1 tensor (include end, depreciated)
one_d = torch.arange(0, 9)
print(one_d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [15]:
two_d = one_d.view(3, -1)
print(two_d)
print(two_d.dim())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
2


## Access item in high dimensional tensor

In [21]:
print(two_d[1, 2])

tensor(5)


In [30]:
x = torch.arange(0, 18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [31]:
x[1, 1, 1]

tensor(10)

## Slice 3D tensor

In [32]:
#slice 6-11
x[1, :, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [33]:
#slice 6, 7, 9, 10
x[1, :, 0:2]

tensor([[ 6,  7],
        [ 9, 10]])