In [1]:
import torch

## Ways to do matrix multiplication

In [5]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
print(mat_a)
print(mat_b)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


In [6]:
#Two ways to do multiplication
print(torch.matmul(mat_a, mat_b))
print(mat_a @ mat_b)

tensor([[ 29, -16],
        [ 38,   6]])
tensor([[ 29, -16],
        [ 38,   6]])


## Matrix Gradient

In [9]:
x = torch.tensor(2.0, requires_grad = True)
y = 9*x**4 + 2*x**3 + 3*x**2 + 6*x + 1
y.backward()
# y = 36x^3 + 6x^2 + 6x + 6, x = 2, 
x.grad

tensor(330.)

In [10]:
x = torch.tensor(1.0, requires_grad = True)
z = torch.tensor(2.0, requires_grad = True)
y = x**2 + z**3
y.backward()
# y = 2x, x = 1
x.grad

tensor(2.)